part of 'therapy_detail_bloc.dart';

@freezed
class TherapyDetailState with _$TherapyDetailState {
  const factory TherapyDetailState({
    required LoadingState loadingState,
    required String? categoryTitle,
    required String? therapyTitle,
    required String? therapyPlace,
    required int? selectedOptionIndex,
    required int? selectedDurationIndex,
    required String? errorMessage,
    required PricingOptionModel? selectedPricingOption,
    required int? selectedOptionQuantity,
    required ServiceType serviceType,
    required PricingOptionModel? initPricingOption,
    required int? initOptionQuantity,
    required ServicePart servicePart,
    required bool isRequireConsultation,
    required bool isBooking,
    required bool canBeBooked,
    required TherapyDetailModel? therapyDetailModel,
    required double? latitude,
    required double? longitude,
    required double? clinicLat,
    required double? clinicLong,
    required String? clinicAddress,
    required String? homeAddress,
    required double? totalPrice,
    required bool isBookingAvailable,
    required String? serviceTypeText,
    required ClinicFinderResponse? finderResponse,
    required TextEditingController addressController,
    required String? therapyDuration,
  }) = _TherapyDetailState;

  factory TherapyDetailState.initialize() => TherapyDetailState(
      loadingState: LoadingState.isInitial,
      categoryTitle: null,
      therapyTitle: null,
      errorMessage: null,
      therapyPlace: 'home-visit',
      selectedPricingOption: null,
      selectedOptionQuantity: null,
      selectedOptionIndex: 0,
      initOptionQuantity: null,
      initPricingOption: null,
      selectedDurationIndex: 0,
      serviceType: ServiceType.Full,
      servicePart: ServicePart.None,
      isRequireConsultation: true,
      isBookingAvailable: true,
      isBooking: false,
      serviceTypeText: '',
      canBeBooked: true,
      latitude: 0,
      longitude: 0,
      clinicLat: 0,
      addressController: TextEditingController(),
      clinicLong: 0,
      totalPrice: 0,
      clinicAddress: '',
      homeAddress: '',
      finderResponse: null,
      therapyDuration: null,
      therapyDetailModel: null);
}
